---
#tasks file for getsysinfo
- name:  Get system info and clean logs
  block:
    - name: Get system info
      import_tasks: sysinfo.yml

    - name: Get system info logs
      import_tasks: sysinfo2logs.yml

